# This is core test runner

image: maxking/mailman-ci-runner

variables:
  POSTGRES_DB: "mailman_test"
  POSTGRES_USER: "runner"
  POSTGRES_PASSWORD: "runner"
  MYSQL_ROOT_PASSWORD: "runner"
  MYSQL_USER: "runner"
  MYSQL_USER_PASSWORD: "runner"
  MYSQL_DATABASE: "test_mailman"
  LC_ALL: "C.UTF-8"


qa:
  script:
  - tox -e qa

docs:
  script:
  - tox -e docs

sqlite-36:
  script:
  - tox -e py36-nocov

sqlite-37:
  script:
  - tox -e py37-nocov

sqlite-38:
  script:
  - tox -e py38-nocov

sqlite-39:
  script:
    - tox -e py39-nocov
  allow_failure: true

pgsql-38:
  services:
  - postgres:latest
  script:
  - MAILMAN_EXTRA_TESTING_CFG=/home/runner/configs/postgres.cfg tox -e py38-nocov-pg
  tags:
  - postgres

pgsql-37:
  services:
  - postgres:latest
  script:
  - MAILMAN_EXTRA_TESTING_CFG=/home/runner/configs/postgres.cfg tox -e py37-nocov-pg
  tags:
  - postgres

mysql-38:
  services:
  - mysql:5.6
  script:
  - MAILMAN_EXTRA_TESTING_CFG=/home/runner/configs/mysql.cfg tox -e py38-nocov-mysql
  tags:
  - mysql

mysql-37:
  services:
  - mysql:5.6
  script:
  - MAILMAN_EXTRA_TESTING_CFG=/home/runner/configs/mysql.cfg tox -e py37-nocov-mysql
  tags:
  - mysql


diffcov:
  script:
  - tox -e py37-diffcov
  except:
  - master
